### ISSUE TITLE
Incompatible with REI 1.17

### ISSUE THREAD

**Issue by shedaniel** [emilyalexandra/pocket-tools#3]
Custom TooltipComponents were not handled in the best way. (see TooltipComponent#of), You may want to mixin that to return a proper value for REI (/or other mods) to render that easier. (Instead of mixing into the lambda in the screen)

https://gist.githubusercontent.com/natanfudge/b6bf3ae6889de475dae42ee36d9c6795/raw/ca6188e7e68fa9ea2d7e57ce3afa9517a018c0eb/crash.txt

**Comment by emilyalexandra** [comment]
Thank you for designing me a solution for a problem your mod created. Unfortunately, your solution does not work and could not possibly work because of the limitations of Mixin. I cannot inject I not `TooltiopComponent#of`, something you would probably know if you tried your solution first. You'll need to correct how you solve this problem on your end and, in the case where other mods may be failing to work how you expect, my personal recommendation is to make sure your proposed solutions are possible before offering it .
